### ISSUE TITLE
调用Image operations中的 imageInfo 和 exif 接口报错

### ISSUE THREAD

**Issue by leekangtaqi** [node-modules/qn#10]
调用Image operations中的 imageInfo 和 exif 接口报错：
[2015-03-16 15:06:39.234] [INFO] console - { [RequestError: connect ECONNREFUSED (req "error"), GET 7u2kxz.com2.z0.glb.qiniucdn.com/user/mytest14.jpg?imageInfo -1
headers: {}]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  name: 'RequestError',
  data: undefined,
  status: -1,
  headers: {},
  res: 
   { status: -1,
     statusCode: -1,
     headers: {},
     size: 0,
     aborted: false,
     rt: 1010 } }
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

**Comment by leekangtaqi** [comment]
能帮忙解决下吗，不胜感激

**Comment by fengmk2** [comment]
直接访问 7u2kxz.com2.z0.glb.qiniucdn.com/user/mytest14.jpg?imageInfo 是 ok 的啊

**Comment by flftfqwxf** [comment]
我也遇到同样的问题

**Comment by flftfqwxf** [comment]
这个图片存在，但是在调用 的时候报错

代码如下： 
client.exif('http://7xi5ze.com1.z0.glb.clouddn.com/Fsy49-5hnXv5miDcKscX2FJ1R6hh', function (err, exif) {
    console.log(err);
    console.log(exif);
});
