### ISSUE TITLE
"co-busboy"  解析流如何处理呢？

### ISSUE THREAD

**Issue by petitspois** [node-modules/qn#12]
现在的代码
```js
post.qnupload = function* (){

        if ('POST' != this.method) return yield next;

        // multipart upload
        var parts = parse(this,{autoFields: true});
        var part = yield parts;

        store.upload(part, function(err, ret){
            console.log(ret)
        });

    }
```
error
```js
TypeError: Cannot read property 'replace' of undefined
      at Mime.lookup (/Users/qingdou/docs.ren/node_modules/qn/node_modules/formstream/node_modules/mime/mime.js:72:17)
      at FormStream.stream (/Users/qingdou/docs.ren/node_modules/qn/node_modules/formstream/lib/formstream.js:147:21)
      at Qiniu.upload (/Users/qingdou/docs.ren/node_modules/qn/lib/up.js:118:12)
      at Object.post.qnupload (/Users/qingdou/docs.ren/controller/post.js:172:15)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/qingdou/docs.ren/node_modules/co/index.js:59:19)
      at runMicrotasksCallback (node.js:337:7)
      at process._tickCallback (node.js:355:11)
```

求解决。。。。

**Comment by petitspois** [comment]
@fengmk2

**Comment by petitspois** [comment]
解决了。
```js
store.upload(part, {filename:part.filename, contentType:part.mimeType}, function(err, ret){
            console.log(ret)
        });
```
或者
part.path 添加filename
:)

**Comment by luck-zzb** [comment]
@petitspois  store.upload这个是引用的哪个？
